# Generated by Django 3.2.14 on 2022-07-07 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20220707_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='description',
            field=models.TextField(default='Write the Note'),
        ),
        migrations.AlterField(
            model_name='notes',
            name='title',
            field=models.CharField(default='Title', max_length=200),
        ),
    ]
